name: Rust

on:
  push:
    branches: 
      - "**"
  pull_request:
    branches: 
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Install rustfmt
        run: rustup component add rustfmt
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose